matrix:
  - name: Markdown
    aspell:
      lang: en
      ignore-case: true
    dictionary:
      wordlists:
        - .github/wordlist.txt
      encoding: utf-8
    pipeline:
      - pyspelling.filters.markdown:
          markdown_extensions:
            - pymdownx.superfences  # Enables handling of fenced code blocks
      - pyspelling.filters.html:
          comments: false
          ignores:
            - code   # Ignore fenced code blocks
            - pre    # Ignore preformatted text (typically used for code)
            - inlinecode  # Ignore inline code snippets (`code`)
            - html   # Ignore HTML content
    sources:
      - './pages/**/*.mdx'  # Specify .mdx files to check within the pages directory
    default_encoding: utf-8
