version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    command: ["./startup.sh"]
    ports:
      - "8000:80"
    environment:
      DATABASE_URL: postgresql://user:pass@db/feedback
    depends_on:
      - db
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    command: ["pnpm", "dev"]
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: feedback
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
