apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "docsServiceName" . }}
  labels:
    app: {{ include "docsServiceName" . }}

spec:
  {{- if .Values.website.hpa.enabled }}
  {{- else }}
  replicas: {{ .Values.website.replicas }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ include "docsServiceName" . }}

  template:
    metadata:
      labels:
        app: {{ include "docsServiceName" . }}

    spec:
      containers:
        - name: docs
          image: "{{ .Values.website.image.repo }}:{{ .Values.website.image.tag }}"
          ports:
            - name: web
              containerPort: 3000

          resources:
            requests:
              cpu: {{ .Values.website.cpuRequest | quote }}
              memory: {{ .Values.website.memRequest | quote }}
            limits:
              cpu: {{ .Values.website.cpuLimit | quote }}
              memory: {{ .Values.website.memLimit | quote }}

          startupProbe:
            httpGet:
              path: /docs
              port: web
            initialDelaySeconds: 0
            periodSeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 6 # allow 30 seconds for the initial start of the application

          livenessProbe:
            httpGet:
              path: /docs
              port: web
            initialDelaySeconds: 0
            periodSeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 12 # allow 60 seconds before killing the pod

          readinessProbe:
            httpGet:
              path: /docs
              port: web
            initialDelaySeconds: 0
            periodSeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 1
