{{ if .Values.ingress.enable }}
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: {{ include "docsServiceName" . }}
  labels:
    app: {{ include "docsServiceName" . }}

spec:
  endpoints:
    - dnsName:  {{ .Values.dns.name }}
      recordTTL: 180
      recordType: CNAME
      targets:
        - {{ .Values.dns.target }}
{{ end }}
