{{ if .Values.ingress.enable }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "docsServiceName" . }}
  labels:
    app: {{ include "docsServiceName" . }}

spec:
  gateways:
    - {{ include "docsServiceName" . }}

  hosts:
    - {{ .Values.dns.name }}
    {{- range .Values.dns.additionalHosts }}
    - {{ . | quote }}
    {{- end }}

  http:
    - route:
        - destination:
            host: {{ include "docsServiceName" . }}
            port:
              number: 80
          weight: 100
{{ end }}
