name: Spell Checking

on:
  pull_request:
    branches:
      - "**"

jobs:
  codespell:
    name: Check Spelling with codespell
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List directory contents
        run: ls -la .github/

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install codespell
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Check spelling with codespell
        run: codespell --ignore-words-list=.github/codespell-custom.txt --skip=".yaml" ./pages/ || exit 1

  misspell:
    name: Check Spelling with misspell
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install misspell
        run: wget -O - -q https://git.io/misspell | sh -s -- -b .

      - name: Run misspell
        run: ./misspell -error ./pages/
